## 講座2.1 Numpy入門

### NumPy 的定義

#### 匯入套件

In [1]:
# 匯入套件
import numpy as np

# numpy 的浮點數表示精度, 小數第 4 位
np.set_printoptions(suppress=True, precision=4)

#### 定義 NumPy 資料

In [2]:
# 定義 NumPy 資料

# 定義 1D 陣列變數
a = np.array([1, 2, 3, 4, 5, 6, 7])

# 定義 2D 陣列變數
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])

#### 顯示內容

In [3]:
# 顯示內容

# 顯示 1D 陣列變數
print(a)

# 顯示 2D 陣列變數
print(b)

[1 2 3 4 5 6 7]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 確認元素數量

In [4]:
# 確認元素數量

# 顯示 1D 陣列變數
print(a.shape)

# 顯示 2D 陣列變數
print(b.shape)

# 利用 len 函式
print(len(a))
print(len(b))

(7,)
(4, 3)
7
4


### NumPy 的操作

#### 提取特定行

In [5]:
# 提取特定行

# 0 行
c = b[:,0]
print(c)

# [0,1] 行
d = b[:,:2]
print(d)

[ 1  4  7 10]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


#### reshape 函式

In [6]:
# reshape 函式

l = np.array(range(12))
print(l)

# 轉換成 3 列 4 行
m = l.reshape((3,4))
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 統計函式

In [7]:
# 統計函式

print(f'原始變數: {a}')

a_sum = np.sum(a)
print(f'總和: {a_sum}')

a_mean = np.mean(a)
print(f'平均值: {a_mean}')

a_max = np.max(a)
print(f'最大值: {a_max}')

a_min = a.min()
print(f'最小值: {a_min}')

原始變數: [1 2 3 4 5 6 7]
總和: 28
平均值: 4.0
最大值: 7
最小值: 1


#### NumPy 變數之間的計算

In [8]:
# 準備 2 個 NumPy 陣列 yt 與 yp
yt = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])
yp = np.array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])
print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


In [9]:
# 同時比較陣列中各元素
w = (yt == yp)
print(w)

[ True  True  True  True  True  True  True False  True  True]


In [10]:
# 再將此結果代入 sum 函式中
print(w.sum())

9


#### 廣播功能

In [11]:
# 廣播功能
print(a)
c = (a - np.min(a)) / (np.max(a) - np.min(a))
print(c)

[1 2 3 4 5 6 7]
[0.     0.1667 0.3333 0.5    0.6667 0.8333 1.    ]


#### 生成數值陣列

In [12]:
# 生成數值陣列
x = np.linspace(-5, 5, 11)
print(x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
